name: Merge CI
on: [pull_request]
jobs:
 Explore-GitHub-Actions:
   runs-on: [ubuntu-latest, windows-latest, macos-latest
   steps:
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
     - run: python main.py